# Generated by Django 4.1.1 on 2022-09-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='product',
            new_name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=10),
        ),
    ]
